name: Update Major Version Tag

on:
  release:
    types: [published]

jobs:
  update-major-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update major version tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          MAJOR_VERSION=$(echo $TAG | cut -d. -f1)
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -f $MAJOR_VERSION $TAG
          git push -f origin $MAJOR_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}